[workspace]
resolver = "2"
members = [
    "crates/qmaws-core",
    "crates/qmaws-engine",
    "crates/qmaws-data",
    "crates/qmaws-viz",
    "crates/qmaws-tui",
    "crates/qmaws-gui",
    "crates/qmaws-cli",
]

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["Sudipta Kumar Das"]
license-file = "LICENSE"
repository = "https://github.com/the-sudipta/q-maws"
publish = false

[profile.release]
debug = false
